Added Project 5.1
EmirVildanov/BasicProgramming pull request #30
Opened 2019-10-21 17:50 UTC by EmirVildanov

2019-11-21 13:41 UTC, SpirinEgor requested changes
Проверь все стрелочки, я мог случайно пропустить

2019-11-21 13:41 UTC, SpirinEgor commented on hw5/task1/STACK_H.c
> +    stackElement ->next = stack ->first;
Лишние пробелы

2019-11-21 13:41 UTC, SpirinEgor commented on hw5/task1/STACK_H.c
> +    stack ->first = poppedElement ->next;
И тут пробел не нужен

2019-11-21 13:41 UTC, SpirinEgor commented on hw5/task1/main.c
> +    }
Не надо так делать, возвращай условие ифа

2019-11-21 13:41 UTC, SpirinEgor commented on hw5/task1/main.c
> +int checkPower(char digit)
Я бы назвал `getPriority`
И на вход всё-таки не цифра приходит, а оператор

2019-11-21 13:41 UTC, SpirinEgor commented on hw5/task1/main.c
> +int main() {
Не тут

2019-11-21 13:41 UTC, SpirinEgor commented on hw5/task1/queue.c
> +    newQueueElement ->next = NULL;
Опять стрелочки не там

2019-11-21 13:41 UTC, SpirinEgor commented on hw5/task1/queue.c
> +}
Точно так надо?

2019-12-18 09:40 UTC, SpirinEgor commented
Валгринд показывает утечку памяти и, иногда, ошибку при чтение значения из переменной (на 1+2 тесте)

2019-12-19 20:21 UTC, fefaleksey requested changes
ну нет, не верю
Please, enter your line without spaces : 1+5
The postfix line is : 15+

Please, enter your line without spaces : sfj34jkh5334jkh34
The postfix line is : sfj34jkh5334jkh34

2019-12-22 12:15 UTC, fefaleksey requested changes
валгринду опять плохо
Please, enter your line : 23lrkj kl23r
Wrong input. Please, enter your line again: welkn lwke
Wrong input. Please, enter your line again: 1 + 5
The postfix line is : 15+

2020-02-22 17:44 UTC, closed without merging