Added project 5.2
EmirVildanov/BasicProgramming pull request #31
Opened 2019-10-21 17:56 UTC by EmirVildanov

2019-11-21 13:44 UTC, SpirinEgor requested changes

2019-11-21 13:44 UTC, SpirinEgor commented on hw5/task2/FLOATSTACK_H.c
> +    newStack ->first = NULL;
В этом пр тоже стрелочки поехали. Проверь все

2019-11-21 13:44 UTC, SpirinEgor commented on hw5/task2/FLOATSTACK_H.c
> +    float value = poppedElement ->value;
А память почистить?

2019-11-21 13:44 UTC, SpirinEgor commented on hw5/task2/main.c
> +    return answer;
опять же, нужно просто вернуть условие (`return (digit == '+') || ...`)

2019-11-21 13:44 UTC, SpirinEgor commented on hw5/task2/main.c
> +            float result =  doOperation(digit, firstDigit, secondDigit);
Пробел лишний

2019-12-18 09:46 UTC, SpirinEgor requested changes

2019-12-18 09:46 UTC, SpirinEgor commented on hw5/task2/main.c
> +    return answer;
Не исправлено

2019-12-18 09:46 UTC, SpirinEgor commented on hw5/task2/main.c
> +    if (operator == '-')
Надо либо через `else` разделять, либо внутри `if` делать `return`.
При такой реализации все 4 условия проверяются всегда, хотя в этом нет необходимости

2019-12-19 20:26 UTC, fefaleksey requested changes
А что мне делать, если я хочу посчитать "256 255 -"?
(да, пробелы могут быть)

2019-12-22 12:23 UTC, fefaleksey requested changes
И тут валгринд

2020-02-22 17:45 UTC, closed without merging