Added 2.1
EmirVildanov/BasicProgramming pull request #33
Opened 2019-10-21 18:31 UTC by EmirVildanov

2019-11-06 14:13 UTC, SpirinEgor requested changes

2019-11-06 14:13 UTC, SpirinEgor commented on hw2/task1/2.1.c
> +int findSmallestElementIndex(int *list, int length, int maxElement, int maxElementIndex)
Последние 2 аргумента не используются. Так же непонятна связь между названием, и телом функции. Если уже передаётся отсортированный массив, то лучше уточнить это в название переменной.

2019-11-06 14:13 UTC, SpirinEgor commented on hw2/task1/2.1.c
> +    }
Для этого есть метод выше

2019-11-24 20:31 UTC, fefaleksey requested changes

2019-11-24 20:31 UTC, fefaleksey commented on hw2/task1/2.1.c
> +                {
Просто units[nextAfterMaxElementIndex] + 1 > maxElement, скобки не нужны

2019-11-24 20:31 UTC, fefaleksey commented on hw2/task1/2.1.c
> +{
Эта функция даже на экран не помещается) разбей ее на более мелкие

2019-12-01 21:01 UTC, fefaleksey approved these changes
ok

2019-12-02 17:13 UTC, merged