Added 3.1
EmirVildanov/BasicProgramming pull request #39
Opened 2019-10-21 18:44 UTC by EmirVildanov

2019-11-06 16:12 UTC, SpirinEgor requested changes

2019-11-06 16:12 UTC, SpirinEgor commented on hw3/task1/main.c
> +        for (int j = 2 * i + 1; j < length; ++j)
Сортировки различаются только в выражение `2 * i + 1` и `2 * i + 2`
Можно передать 1 или 2 параметром, тогда вместо 2 функций будет всего 1.

2019-11-06 16:12 UTC, SpirinEgor commented on hw3/task1/main.c
> +void changePlaces(int list[], int first, int second)
Обычно называют `swap`

2019-11-20 10:18 UTC, SpirinEgor commented on hw3/task1/main.c
> +    }
Я имел ввиду, что вот этот кусок можно вынести в отдельную функцию.
Тогда в `heapSort` будет 2 вызова:
```(C)
heapify(list, length - i, 1)
heapify(list, length - i, 2)
```

2019-11-20 10:18 UTC, SpirinEgor commented on hw3/task1/main.c
> +    }
Сейчас у тебя по-прежнему 2 куска с одинаковым кодом идут друг за другом

2019-11-24 20:16 UTC, fefaleksey approved these changes
ок

2019-11-24 20:16 UTC, fefaleksey commented on hw3/task1/main.c
> +    return 0;
В конце в будущем делай перенос строки, иначе в консоле получается
Sorted array is : 0 1 2 2 4 4 5 5 5 7 aleksey@aleksey:~$

2019-11-25 08:06 UTC, merged