Added 3.2
EmirVildanov/BasicProgramming pull request #40
Opened 2019-10-21 18:45 UTC by EmirVildanov

2019-11-06 16:19 UTC, SpirinEgor requested changes

2019-11-06 16:19 UTC, SpirinEgor commented on hw3/task2/main.c
> +            if (fgets(newline,100, file) != NULL)
Не хватает пробела перед 100. И это число лучше вынести как константу-параметр

2019-11-06 16:19 UTC, SpirinEgor commented on hw3/task2/main.c
> +    char *newline = createCharArray((maxSize));
Мне кажется, что здесь хватит и одной пары скобок.

2019-11-06 16:19 UTC, SpirinEgor commented on hw3/task2/main.c
> +            if (fgets(newline,100, file) != NULL)
Тем более зачем создавать строку длиной 1000, а использовать только 100.

2019-11-20 10:22 UTC, SpirinEgor requested changes

2019-11-20 10:22 UTC, SpirinEgor commented on hw3/task2/main.c
> +    else
Так как в `if` стоит выход из программы, то `else` можно не использовать

2019-11-20 10:22 UTC, SpirinEgor commented on hw3/task2/main.c
> +        exit(1);
Лучше сделать `return` с ненулевым кодом возврата

2019-11-20 10:22 UTC, SpirinEgor commented on hw3/task2/main.c
> +        exit(1);
`exit` -- останавливает текущий процесс, причём это не инструкция языка, а системный вызов

2019-11-24 20:20 UTC, fefaleksey requested changes
Почти ок, только на функции ещё разбей
P.S. название последнего коммита не очень отражает суть изменений

2019-11-24 20:20 UTC, fefaleksey commented on hw3/task2/main.c
> +    FILE *file = fopen("text", "r");
Тут тоже разбей на функции и будет ок

2019-12-01 22:36 UTC, fefaleksey approved these changes
ok

2019-12-02 17:12 UTC, merged