Added 3.3
EmirVildanov/BasicProgramming pull request #41
Opened 2019-10-21 18:46 UTC by EmirVildanov

2019-11-06 16:24 UTC, SpirinEgor requested changes

2019-11-06 16:24 UTC, SpirinEgor commented on hw3/task3/main.c
> +void replace(int list[], int first, int second)
Обычно называют `swap`

2019-11-06 16:24 UTC, SpirinEgor commented on hw3/task3/main.c
> +void moveTheNulls(int list[], int length)
Надо нули двигать, переводится как `zero`

2019-11-06 16:24 UTC, SpirinEgor commented on hw3/task3/main.c
> +int findNoNullIndex(int list[], int length, int nullIndex)
`findNotZeroIndex`
Но лучше ещё как-то передать, что первый с конца.

2019-11-06 16:24 UTC, SpirinEgor commented on hw3/task3/main.c
> +        }
Это условие можно передать в цикл, `(list[index] == 0 && index > 0)`

2019-11-06 16:24 UTC, SpirinEgor commented on hw3/task3/main.c
> +    }
Такого не может быть, так как когда `while` дойдёт до `nullIndex`, он его вернёт.

2019-11-06 16:24 UTC, SpirinEgor commented on hw3/task3/main.c
> +    }
И опять же, не `null`, а `zero`

2019-11-06 16:24 UTC, SpirinEgor commented on hw3/task3/main.c
> +        }
И оно даже не нужно, так как функция вызывается, когда найден 0, то есть что-то точно вернётся.

2019-12-01 22:36 UTC, fefaleksey approved these changes
ok

2019-12-02 17:11 UTC, merged