Added 3.4.c file
EmirVildanov/BasicProgramming pull request #42
Opened 2019-10-21 18:47 UTC by EmirVildanov

2019-11-06 16:49 UTC, SpirinEgor requested changes

2019-11-06 16:49 UTC, SpirinEgor commented on hw3/task4/main.c
> +int checkAppropriateUsers(int numberOfUsers, int actions, int timer)
Лучше разделить ввод и решений, пусть ввод полностью будет в `main`, а здесь уже решение.

2019-11-20 10:40 UTC, SpirinEgor requested changes

2019-11-20 10:40 UTC, SpirinEgor commented on hw3/task4/main.c
> +int main() {
Эх, скобка не там

2019-11-20 10:40 UTC, SpirinEgor commented on hw3/task4/main.c
> +        for(int i = 0; i < numberOfActions; ++i)
А тут пробела не хватает

2019-11-20 10:40 UTC, SpirinEgor commented on hw3/task4/main.c
> +void checkAppropriateUsers(int numberOfActions, int* numbers, int numberOfUsers, int actions, int timer, int* answer)
А для чего `answer` передавать?
Функция проверяет пользователя, то есть уместнее назвать `isAppropriatedUser`, чтобы она возвращала `bool`, а `main` делать +1, если вернулось `true`

2019-11-24 20:17 UTC, fefaleksey requested changes
Разбей на функции и будет ок

2019-11-24 20:17 UTC, fefaleksey commented on hw3/task4/main.c
> +}
Вот это все же стоит разбить на более мелкие функции

2019-12-01 22:37 UTC, fefaleksey approved these changes
ok

2019-12-02 17:10 UTC, merged