Added project 4.1
EmirVildanov/BasicProgramming pull request #43
Opened 2019-10-26 10:37 UTC by EmirVildanov

2019-11-06 17:13 UTC, SpirinEgor requested changes

2019-11-06 17:13 UTC, SpirinEgor commented on hw4/task1/List.c
> +        list->lowestElement->lifeStatus = true;
Эти 2 строчки есть в обоих ветках условиях, можно вынести

2019-11-06 17:13 UTC, SpirinEgor commented on hw4/task1/List.h
> +#ifndef INC_4_2_LIST_H
Какое-то странное название дефайна

2019-11-06 17:13 UTC, SpirinEgor commented on hw4/task1/main.c
> +    if (checkLifeStatus(currentUnit))
`findAliveUnit` уже находит следующего не убитого, поэтому непонятно, зачем такая проверка.

2019-11-06 17:13 UTC, SpirinEgor commented on hw4/task1/main.c
> +    return currentUnit;
Если `currentUnit` уже убит, то отсчёт должен начинаться со следующего.

2019-11-06 17:13 UTC, SpirinEgor commented on hw4/task1/main.c
> +    while (aliveUnitsNumber != 1)
Вместо использования цикла `while`, можно сделать цикл по количеству солдатов, тогда и в функции будет меньше параметров.

2019-11-21 10:20 UTC, SpirinEgor requested changes

2019-11-21 10:20 UTC, SpirinEgor commented on hw4/task1/List.c
> +struct ListElement{
Фигурные скобки ставятся со следующей строчки

2019-11-21 10:20 UTC, SpirinEgor commented on hw4/task1/List.c
> +struct List{
Аналогично

2019-11-21 10:20 UTC, SpirinEgor commented on hw4/task1/List.c
> +        list->lowestElement->lifeStatus = true;
Ничего же не поменялось.
Для `listElement` можно задать поля `number` и `lifeStatus` вне `if`

2019-11-21 10:20 UTC, SpirinEgor commented on hw4/task1/main.c
> +int main() {
И опять скобочка

2019-12-01 22:38 UTC, fefaleksey requested changes

2019-12-01 22:38 UTC, fefaleksey commented on hw4/task1/List.h
> +#pragma one
Не исправил

2019-12-02 17:08 UTC, jzuken requested changes

2019-12-02 17:08 UTC, jzuken commented on hw4/task1/List.c
> +        exit(1);
не надо так, пожалуйста, делать. функция должна что-то вернуть, особенно из стороннего модуля это не в её правах завершать приложение

2019-12-02 17:08 UTC, jzuken commented on hw4/task1/List.c
> +    listElement->lifeStatus = status;
а есть какая-то причина, по которой ты просто не удаляешь из списка убитых юнитов?

2019-12-10 11:46 UTC, merged