Added project 4.2
EmirVildanov/BasicProgramming pull request #44
Opened 2019-10-26 12:32 UTC by EmirVildanov

2019-11-06 17:30 UTC, SpirinEgor requested changes

2019-11-06 17:30 UTC, SpirinEgor commented on hw4/task2/Array.h
> +#ifndef ARRAY_ARRAY_H
БОЛЬШЕ ARRAY

2019-11-06 17:30 UTC, SpirinEgor commented on hw4/task2/Commands.h
> +#ifndef INC_4_2_COMMANDS_H
Что за INC_4_2?

2019-11-06 17:30 UTC, SpirinEgor commented on hw4/task2/List.h
> +#endif
Интересно

2019-11-06 17:30 UTC, SpirinEgor commented on hw4/task2/List.h
> +    char name[15];
Константы следует выносить

2019-11-06 17:30 UTC, SpirinEgor commented on hw4/task2/List.c
> +    newElement->next = list->first;
В листе же элементы обычно добавляют в конец. Хотя для решения это, видимо, не важно

2019-11-06 17:30 UTC, SpirinEgor commented on hw4/task2/List.c
> +    while (strcmp(currentNumber->number, "404") != 00)
Что за странная проверка?

2019-11-06 17:30 UTC, SpirinEgor commented on hw4/task2/List.c
> +    while (strcmp(currentNumber->number, "404") != 00)
Аналогично, что за номер 404

2019-11-06 17:30 UTC, SpirinEgor commented on hw4/task2/List.c
> +    }
Для чего 2 раза проходить по листу, можно же сделать за один проход без доп функций. Если имя совпало, то возвращаем номер в этой вершине. Если прошли весь лист, то такого имени нет

2019-11-06 17:30 UTC, SpirinEgor commented on hw4/task2/List.c
> +    }
Такое же замечание

2019-11-06 17:30 UTC, SpirinEgor commented on hw4/task2/main.c
> +    addNew(numberList, "404", "support", numberIndex, maxValueSize);
Зачем это? Если для обозначения конца листа, то это не нужно, там должна быть проверка на `NULL`

2019-11-21 10:34 UTC, SpirinEgor requested changes
Не очень понял, зачем нужна переменная `numberIndex`, по смыслу она похоже на размер листа, но тогда лучше внести её в структуру и использовать `numberList->size`

2019-11-21 10:34 UTC, SpirinEgor commented on hw4/task2/Commands.c
> +void entrance() {
:disappointed:

2019-11-21 10:34 UTC, SpirinEgor commented on hw4/task2/Commands.h
> +#ifndef INC_4_2_COMMANDS_H
По-прежнему осталось

2019-11-21 10:34 UTC, SpirinEgor commented on hw4/task2/List.c
> +
Наплодил строчек

2019-11-21 10:34 UTC, SpirinEgor commented on hw4/task2/List.h
> +#define valueSize 15
`const`

2019-11-21 10:34 UTC, SpirinEgor commented on hw4/task2/List.h
> +struct ListElement{
Со следующей строчки

2019-11-21 10:34 UTC, SpirinEgor commented on hw4/task2/List.h
> +struct List{
Не там

2019-11-21 10:34 UTC, SpirinEgor commented on hw4/task2/main.c
> +    ++numberIndex;
Можно сразу 1 проинициализировать

2019-12-10 11:51 UTC, jzuken requested changes

2019-12-10 11:51 UTC, jzuken commented on hw4/task2/main.c
> +int main()
открыл, вышел и сразу потерял 46 байт

2019-12-10 11:51 UTC, jzuken commented on hw4/task2/main.c
> +void readFile(FILE* file, List* numberList)
записал имя и телефон в файл, вышел, зашёл, их не находит больше

2019-12-10 11:51 UTC, jzuken commented on hw4/task2/Commands.c
> +        return 1;
а это что за константы волшебные? завел бы enum лучше

2019-12-10 11:51 UTC, jzuken commented on hw4/task2/Commands.h
> +void entrance();
обычно оно называется usage

2019-12-10 11:51 UTC, jzuken commented on hw4/task2/List.c
> +char* findNumber(List* list, char name[])
почему в модуле списка появились какие-то номера? в модуле списка должен быть список, а телефонная книжка в модуле телефонной книжки

2019-12-17 13:21 UTC, SpirinEgor requested changes
Теперь у тебя несколько функций дублируются в List.h и PhoneBook.h, например `getNumberIndex`

Если ты что-то переименовал, то старое надо удалить

2019-12-19 20:13 UTC, fefaleksey requested changes
Ну камон

In file included from /home/aleksey/programs/spbu-19/vildanov/BasicProgramming/hw4/task2/main.c:5:0:
/home/aleksey/programs/spbu-19/vildanov/BasicProgramming/hw4/task2/Commands.h:2:10: fatal error: List.h: No such file or directory
 #include "List.h"

2019-12-19 20:13 UTC, fefaleksey commented on hw4/task2/main.c
> +const int maxInputSize = 15;
В условии нет такого ограничения

2019-12-23 14:42 UTC, SpirinEgor commented
Запуск валгринда на приложенном файле даёт кучу ошибок

2020-02-22 17:45 UTC, closed without merging