Added 4.3
EmirVildanov/BasicProgramming pull request #45
Opened 2019-10-26 12:53 UTC by EmirVildanov

2019-11-21 10:47 UTC, SpirinEgor requested changes

2019-11-21 10:47 UTC, SpirinEgor commented on hw4/task3/main.c
> +}
1. Не используется аргумент `direction`
2. Не надо выводить внутри этих функций, они за другое отвечают (если убрать вывод, то опять же появится неиспользуемый аргумент -- лист)

4 функции можно сократить до 2: движение по первому индексу и по второму (тогда уже direction перестанет быть бесполезным)

2019-11-21 10:47 UTC, SpirinEgor commented on hw4/task3/main.c
> +    }
И здесь упроститься, будет 2 вызова: движение по горизонтали и вертикали, в которые просто передаёшь текущий direction

2019-11-21 10:47 UTC, SpirinEgor commented on hw4/task3/main.c
> +int main() {
:no_entry_sign:

2019-12-01 22:39 UTC, fefaleksey approved these changes
ok

2019-12-02 17:09 UTC, jzuken requested changes

2019-12-02 17:09 UTC, jzuken commented on hw4/task3/main.c
> +void moveNumber(int **list, int* spiralArray, int *currentElementIndex1, int *currentElementIndex2, int direction, int length, int side, int* spiralArrayIndex)
длинновата строка

2019-12-02 17:09 UTC, jzuken commented on hw4/task3/main.c
> +        exit(1);
та же история, не надо вообще этот exit использовать нигде

2019-12-10 11:52 UTC, merged