Added project 6.3
EmirVildanov/BasicProgramming pull request #49
Opened 2019-10-29 20:18 UTC by EmirVildanov

2019-12-08 17:06 UTC, jzuken requested changes

2019-12-08 17:06 UTC, jzuken commented on hw6/task3/main.c
> +int main()
а тут тоже интерактивного режима не наблюдается

2019-12-08 17:06 UTC, jzuken commented on hw6/task3/Set.c
> +        exit(1);
я уже писал, не надо делать exit из модулей, это очень некрасиво

2019-12-08 17:06 UTC, jzuken commented on hw6/task3/Set.c
> +        return true;
:(

2019-12-08 17:06 UTC, jzuken commented on hw6/task3/Set.c
> +void deleteElement(Set *set, int value)
огроменная функция

2019-12-08 17:06 UTC, jzuken commented on hw6/task3/Set.h
> +
эти пустые строки тут зачем? лучше сгруппируй эти функции по смыслу

2019-12-19 11:21 UTC, SpirinEgor requested changes

2019-12-19 11:21 UTC, SpirinEgor commented on hw6/task3/Set.c
> +        return true;
:(

2019-12-19 11:21 UTC, SpirinEgor commented on hw6/task3/array.c
> +        exit(1);
Про `exit` уже много раз было сказано

2019-12-19 11:21 UTC, SpirinEgor commented on hw6/task3/main.c
> +        case 1:
каждый case выделяется `{}`

2019-12-20 16:46 UTC, SpirinEgor commented
Падает, если удалять элемент, которого нет

2019-12-23 16:14 UTC, SpirinEgor requested changes

2019-12-23 16:14 UTC, SpirinEgor commented on hw6/task3/Set.c
> +        return true;
Уже 3 ревью это не исправляется...

2020-02-22 17:45 UTC, closed without merging