Added project 7.1
EmirVildanov/BasicProgramming pull request #50
Opened 2019-11-10 19:58 UTC by EmirVildanov

2019-12-08 17:24 UTC, jzuken requested changes

2019-12-08 17:24 UTC, jzuken commented on hw7/task1/main.c
> +int main()
тут замечания, аналогичные 6.3

2019-12-19 12:01 UTC, SpirinEgor requested changes

2019-12-19 12:01 UTC, SpirinEgor commented on hw7/task1/Set.c
> +    }
`return set == NULL || set->root == NULL`

2019-12-19 12:01 UTC, SpirinEgor commented on hw7/task1/array.c
> +        exit(1);
Про `exit` много раз было сказано

2019-12-19 12:01 UTC, SpirinEgor commented on hw7/task1/main.c
> +            printf("Enter the value tou want to add : ");
Для `case` также используются `{ }`

2019-12-20 16:56 UTC, SpirinEgor commented
Падает при удаление несуществующего элемента

2020-02-22 17:45 UTC, closed without merging