Added project 7.2
EmirVildanov/BasicProgramming pull request #51
Opened 2019-11-11 20:38 UTC by EmirVildanov

2019-11-24 20:54 UTC, fefaleksey requested changes
Куча лишних файлов (в т.ч. из других задач), разберись с репозиторием

2019-11-24 20:54 UTC, fefaleksey commented on hw7/task2/Array.h
> +#define ARRAY_H
#pragma once

2019-11-24 20:54 UTC, fefaleksey commented on hw7/task2/String.c
> +    {
А если NULL?

2019-11-24 20:54 UTC, fefaleksey commented on hw7/task2/String.c
> +    {
И тут

2019-11-24 20:54 UTC, fefaleksey commented on hw7/task2/String.c
> +    for (int i = 0; i < string->length; ++i)
А ещё тут и везде дальше по коду нужно проверять входные данные

2019-11-24 20:54 UTC, fefaleksey commented on hw7/task2/String.c
> +    {
else не нужен, это и так else (т.к. внутри условия return)

2019-11-24 20:54 UTC, fefaleksey commented on hw7/task2/String.c
> +{
Название не очень, лучше toCharPtr хотябы

2019-11-24 20:54 UTC, fefaleksey commented on hw7/task2/String.c
> +    return charString;
В си строки заканчиваются на '\0'

2019-11-24 20:54 UTC, fefaleksey commented on hw7/task2/Array.c
> +char* createCharArray(size)
What?

2019-11-25 08:13 UTC, jzuken requested changes

2019-11-25 08:13 UTC, jzuken commented on hw7/task2/cmake-build-debug/7_2.cbp
> +<?xml version="1.0" encoding="UTF-8"?>
а вот это всё не надо выкладывать в гит, пожалуйста, это генерящиеся файлы. хочешь выложить конфиг для сборки, выкладывай CMakeLists.txt

2019-11-25 08:13 UTC, jzuken commented on hw7/task2/main.c
> +    String *addingString = createString(charAddingString);
хоть это и игрушечный проверочный файл, тут тоже надо за памятью следить

2019-12-01 22:41 UTC, fefaleksey commented on hw7/task2/main.c
> +}
return?

2019-12-02 10:49 UTC, fefaleksey approved these changes
ок

2019-12-02 17:05 UTC, jzuken commented
а тут конфликт с мастером

2019-12-22 05:31 UTC, merged