Added project 7.3
EmirVildanov/BasicProgramming pull request #55
Opened 2019-11-19 19:16 UTC by EmirVildanov

2019-12-08 16:29 UTC, jzuken requested changes

2019-12-08 16:29 UTC, jzuken commented on hw7/task3/main.c
> +        printf("\nPlease put your file in the build-debug directory");
чего? какая ещё билд директория? я вообще из консоли запускаю, я даже не знаю, где это должно быть

2019-12-08 16:29 UTC, jzuken commented on hw7/task3/main.c
> +    FILE *file = fopen("Test", "rt");
файл хорошо бы прикладывать. я попытался запустить это на main.c, оно упало :(

2019-12-08 16:29 UTC, jzuken commented on hw7/task3/main.c
> +int hashFunction(String* string, int currentLength)
всё, что связано с хештаблицей, хорошо бы вынести в отдельный модуль. очевидно же :)

2019-12-08 16:29 UTC, jzuken commented on hw7/task3/main.c
> +        hashNumber += (getChar(string, i) - 'a' + 1) * numberPower;
а тут не может случиться переполнения интов?

2019-12-20 16:43 UTC, SpirinEgor commented
В Array.c и array.c объявляются одинаковые функции

2020-02-22 17:45 UTC, closed without merging